version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Install libraries"
          command: "npm install"
      - run:
          name: "Run Unit-Tests"
          command: "npm run test"
      - run:
          name: "Downloading wiki"
          command: "git clone https://github.com/OpusCapita/duriel.wiki.git wiki"
      - run:
          name: "Building docs"
          command: "npm run build-docs"
      - run:
          name: "Uploading wiki"
          command: "cd wiki ; git add --all . ; git commit -am 'Updated wiki.' ; git push ; (exit 0)"

workflows:
  version: 2
  commit:
    jobs:
      - build